version: '3.3'

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=Mess
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - mess_network

  fe_container:
    image: suchibhargav/mess_management_frnt:latest
    container_name: fe_container
    build: /home/suchi/Documents/spe_major/frontent/mess/.
    ports:
      - "3000:80"
    links:
      - be_container
    networks:
      - mess_network

  be_container:
    image: suchibhargav/mess_management_bkd:latest
    depends_on:
      - mysqldb
    container_name: be_container
    build: .
    expose:
      - "8087"
    restart: on-failure
    env_file: .env
    ports:
      - "8087:8087"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : root,
        "spring.datasource.password" : 123,
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    networks:
      - mess_network
    stdin_open: true
    tty: true
volumes:
  db:
networks:
  cms_network:
    driver: bridge
