version: '3'
services:
  mess-frontend:
    image: suchibhargav/mess-frontend:latest
    build: /home/suchi/Documents/spe_major/frontent/frontent-mess
    ports:
      - 3000:3000
    depends_on:
      - mess-backend

  mess-backend:
    # container_name: spring-backend
    image: suchibhargav/mess_management_bkd:latest
    restart: on-failure
    build: .
    ports:
      - 8087:8087
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=Mess
      - MYSQL_ROOT_PASSWORD=root
